[project]
name = "kubeflow-model-registry-demo"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kserve==0.13",
    "model-registry==0.2.14",
]
